-- ============================================================================
-- 04_gold_dimensions.sql                    (database: abc_hub_analytics)
--
-- GOLD dimensions shared (conformed) by the three star schemas of Q7.
--
--   dim_date               calendar day           (Scenario A, C)
--   dim_month              calendar month         (Scenario B) - roll-up of dim_date
--   dim_customer           SCD Type 2             (Scenario A)
--   dim_subscription_plan  SCD Type 1             (Scenario A)
--   dim_content            SCD Type 1             (Scenario B, C)
--   dim_warehouse          SCD Type 1             (Scenario C)
--   dim_inventory_item     SCD Type 2             (Scenario C)
--
-- Conventions (as in the course's gold layer):
--   <name>_key   surrogate key (identity), used by facts
--   <name>_id    natural / business key from the source system
--   effective_from / effective_to / is_current   SCD2 validity (DATE grain,
--                because every fact joins on a calendar day)
--   key -1       "Unknown" member so facts never break referential integrity
-- ============================================================================

-- ----------------------------------------------------------------------------
-- dim_date - one row per calendar day. Smart key YYYYMMDD.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS gold.dim_date (
    date_key            INT          PRIMARY KEY,           -- 20250606
    full_date           DATE         NOT NULL UNIQUE,
    day_of_month        SMALLINT     NOT NULL,
    day_of_week         SMALLINT     NOT NULL,              -- ISO: 1 = Monday
    day_name            VARCHAR(10)  NOT NULL,
    is_weekend          BOOLEAN      NOT NULL,
    iso_week            SMALLINT     NOT NULL,
    month_key           INT          NOT NULL,              -- 202506, joins dim_month
    month_number        SMALLINT     NOT NULL,
    month_name          VARCHAR(10)  NOT NULL,
    quarter_number      SMALLINT     NOT NULL,
    year_number         SMALLINT     NOT NULL,
    year_month_label    CHAR(7)      NOT NULL               -- '2025-06'
);

-- ----------------------------------------------------------------------------
-- dim_month - one row per calendar month. Smart key YYYYMM.
-- A shrunken roll-up dimension of dim_date for monthly-grain facts.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS gold.dim_month (
    month_key           INT          PRIMARY KEY,           -- 202506
    month_start_date    DATE         NOT NULL UNIQUE,
    month_end_date      DATE         NOT NULL,
    days_in_month       SMALLINT     NOT NULL,
    month_number        SMALLINT     NOT NULL,
    month_name          VARCHAR(10)  NOT NULL,
    quarter_number      SMALLINT     NOT NULL,
    year_number         SMALLINT     NOT NULL,
    year_month_label    CHAR(7)      NOT NULL
);

-- ----------------------------------------------------------------------------
-- dim_customer - SCD Type 2.
--   Type 2 (new version on change): status, home city / country
--     -> "which country was this customer in when they streamed?"
--   Type 1 (overwrite all versions): name, e-mail, phone, gender, DOB
--     -> corrections, no analytical need for history
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS gold.dim_customer (
    customer_key        BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id         BIGINT       NOT NULL,
    customer_no         VARCHAR(20)  NOT NULL,
    full_name           VARCHAR(201) NOT NULL,
    email               VARCHAR(150),
    phone               VARCHAR(30),
    gender              VARCHAR(20)  NOT NULL,
    date_of_birth       DATE,
    age_band            VARCHAR(20)  NOT NULL,              -- age at registration
    registration_date   DATE,
    registration_month  CHAR(7),                            -- cohort, e.g. '2025-06'
    customer_status     VARCHAR(20)  NOT NULL,              -- SCD2
    home_city           VARCHAR(100) NOT NULL,              -- SCD2
    home_country        VARCHAR(100) NOT NULL,              -- SCD2
    home_country_code   VARCHAR(5)   NOT NULL,              -- SCD2
    scd2_hash           CHAR(32)     NOT NULL,              -- md5 of the SCD2 attributes
    effective_from      DATE         NOT NULL,
    effective_to        DATE         NOT NULL DEFAULT DATE '9999-12-31',
    is_current          BOOLEAN      NOT NULL DEFAULT TRUE,
    source_system       VARCHAR(50)  NOT NULL DEFAULT 'abc_hub_operational',
    _run_id             BIGINT,
    _loaded_at          TIMESTAMP    NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT ck_dim_customer_validity CHECK (effective_to >= effective_from)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_customer_current
    ON gold.dim_customer (customer_id) WHERE is_current;          -- one current version per customer
CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_customer_version
    ON gold.dim_customer (customer_id, effective_from);
CREATE INDEX IF NOT EXISTS ix_dim_customer_lookup
    ON gold.dim_customer (customer_id, effective_from, effective_to);

-- ----------------------------------------------------------------------------
-- dim_subscription_plan - SCD Type 1. Key 0 = "No active subscription".
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS gold.dim_subscription_plan (
    subscription_plan_key INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id             BIGINT       NOT NULL UNIQUE,
    plan_name           VARCHAR(50)  NOT NULL,
    monthly_fee         NUMERIC(10,2),
    video_quality       VARCHAR(20),
    max_devices         INT,
    plan_tier           SMALLINT     NOT NULL,              -- 1 = cheapest; sorts plans
    source_system       VARCHAR(50)  NOT NULL DEFAULT 'abc_hub_operational',
    _run_id             BIGINT,
    _loaded_at          TIMESTAMP    NOT NULL DEFAULT clock_timestamp()
);

-- ----------------------------------------------------------------------------
-- dim_content - SCD Type 1. Streaming and physical titles in one conformed
-- dimension, so streaming and rentals can be analysed together.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS gold.dim_content (
    content_key         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id          BIGINT       NOT NULL UNIQUE,
    title               VARCHAR(255) NOT NULL,
    content_type        VARCHAR(50)  NOT NULL,
    is_streamable       BOOLEAN      NOT NULL,
    is_rentable         BOOLEAN      NOT NULL,
    availability        VARCHAR(20)  NOT NULL,              -- 'Streaming only' / 'Rental only' / 'Streaming & Rental'
    primary_genre       VARCHAR(50)  NOT NULL,
    genre_list          VARCHAR(500) NOT NULL,
    primary_artist      VARCHAR(150) NOT NULL,
    primary_artist_role VARCHAR(50)  NOT NULL,
    language            VARCHAR(50)  NOT NULL,
    age_rating          VARCHAR(10)  NOT NULL,
    release_date        DATE,
    release_year        SMALLINT,
    duration_minutes    INT,
    duration_band       VARCHAR(20)  NOT NULL,
    source_system       VARCHAR(50)  NOT NULL DEFAULT 'abc_hub_operational',
    _run_id             BIGINT,
    _loaded_at          TIMESTAMP    NOT NULL DEFAULT clock_timestamp()
);

-- ----------------------------------------------------------------------------
-- dim_warehouse - SCD Type 1 (location flattened in: city, country).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS gold.dim_warehouse (
    warehouse_key       INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id        BIGINT       NOT NULL UNIQUE,
    warehouse_name      VARCHAR(150) NOT NULL,
    city                VARCHAR(100) NOT NULL,
    country             VARCHAR(100) NOT NULL,
    country_code        VARCHAR(5)   NOT NULL,
    source_system       VARCHAR(50)  NOT NULL DEFAULT 'abc_hub_operational',
    _run_id             BIGINT,
    _loaded_at          TIMESTAMP    NOT NULL DEFAULT clock_timestamp()
);

-- ----------------------------------------------------------------------------
-- dim_inventory_item - SCD Type 2 on status, condition and warehouse
-- (a copy moving warehouse or being retired must not rewrite history).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS gold.dim_inventory_item (
    inventory_key       BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_id        BIGINT       NOT NULL,
    barcode             VARCHAR(50)  NOT NULL,
    content_id          BIGINT       NOT NULL,
    purchase_date       DATE,
    in_service_date     DATE,                               -- LEAST(purchase_date, first rental)
    item_condition      VARCHAR(20)  NOT NULL,              -- SCD2
    item_status         VARCHAR(20)  NOT NULL,              -- SCD2
    warehouse_id        BIGINT       NOT NULL,              -- SCD2
    scd2_hash           CHAR(32)     NOT NULL,
    effective_from      DATE         NOT NULL,
    effective_to        DATE         NOT NULL DEFAULT DATE '9999-12-31',
    is_current          BOOLEAN      NOT NULL DEFAULT TRUE,
    source_system       VARCHAR(50)  NOT NULL DEFAULT 'abc_hub_operational',
    _run_id             BIGINT,
    _loaded_at          TIMESTAMP    NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT ck_dim_inventory_validity CHECK (effective_to >= effective_from)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_inventory_current
    ON gold.dim_inventory_item (inventory_id) WHERE is_current;
CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_inventory_version
    ON gold.dim_inventory_item (inventory_id, effective_from);
CREATE INDEX IF NOT EXISTS ix_dim_inventory_lookup
    ON gold.dim_inventory_item (inventory_id, effective_from, effective_to);

-- ----------------------------------------------------------------------------
-- Unknown / special members (fixed keys, inserted once)
-- ----------------------------------------------------------------------------
INSERT INTO gold.dim_date (date_key, full_date, day_of_month, day_of_week, day_name, is_weekend, iso_week,
                           month_key, month_number, month_name, quarter_number, year_number, year_month_label)
VALUES (-1, DATE '1900-01-01', 0, 0, 'Unknown', FALSE, 0, -1, 0, 'Unknown', 0, 0, 'Unknown')
ON CONFLICT DO NOTHING;

INSERT INTO gold.dim_month (month_key, month_start_date, month_end_date, days_in_month, month_number,
                            month_name, quarter_number, year_number, year_month_label)
VALUES (-1, DATE '1900-01-01', DATE '1900-01-31', 0, 0, 'Unknown', 0, 0, 'Unknown')
ON CONFLICT DO NOTHING;

INSERT INTO gold.dim_customer (customer_key, customer_id, customer_no, full_name, gender, age_band,
                               customer_status, home_city, home_country, home_country_code, scd2_hash,
                               effective_from)
VALUES (-1, -1, 'UNKNOWN', 'Unknown customer', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', '??',
        md5('unknown'), DATE '1900-01-01')
ON CONFLICT DO NOTHING;

INSERT INTO gold.dim_subscription_plan (subscription_plan_key, plan_id, plan_name, monthly_fee, plan_tier)
VALUES (-1, -1, 'Unknown', NULL, 99),
       ( 0,  0, 'No active subscription', 0, 0)
ON CONFLICT DO NOTHING;

INSERT INTO gold.dim_content (content_key, content_id, title, content_type, is_streamable, is_rentable,
                              availability, primary_genre, genre_list, primary_artist, primary_artist_role,
                              language, age_rating, duration_band)
VALUES (-1, -1, 'Unknown content', 'Unknown', FALSE, FALSE, 'Unknown', 'Unknown', 'Unknown', 'Unknown',
        'Unknown', 'Unknown', 'Unknown', 'Unknown')
ON CONFLICT DO NOTHING;

INSERT INTO gold.dim_warehouse (warehouse_key, warehouse_id, warehouse_name, city, country, country_code)
VALUES (-1, -1, 'Unknown warehouse', 'Unknown', 'Unknown', '??')
ON CONFLICT DO NOTHING;

INSERT INTO gold.dim_inventory_item (inventory_key, inventory_id, barcode, content_id, item_condition,
                                     item_status, warehouse_id, scd2_hash, effective_from)
VALUES (-1, -1, 'UNKNOWN', -1, 'Unknown', 'Unknown', -1, md5('unknown'), DATE '1900-01-01')
ON CONFLICT DO NOTHING;
